# Generated by Django 4.1.2 on 2022-10-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('shop', models.CharField(max_length=255)),
                ('maziwa_kubwa', models.IntegerField()),
                ('maziwa_ndogo', models.IntegerField()),
                ('premimum', models.IntegerField()),
                ('daily_hope', models.IntegerField()),
                ('geocoords', models.BigIntegerField(null=True)),
            ],
        ),
    ]
