# Generated by Django 4.1.2 on 2022-10-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='time',
            field=models.TextField(),
        ),
    ]
