# Generated by Django 4.1.2 on 2022-10-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayta', '0002_alter_excel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='geocoords',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='excel',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
