# Generated by Django 4.1.2 on 2022-10-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayta', '0002_alter_excel_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excel',
            old_name='name',
            new_name='submitted_by',
        ),
        migrations.AlterField(
            model_name='excel',
            name='time',
            field=models.TimeField(),
        ),
    ]
