# Generated by Django 4.1.2 on 2022-10-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayta', '0003_alter_excel_geocoords_alter_excel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='time',
            field=models.TimeField(),
        ),
    ]
